# Generated by Django 5.2 on 2025-04-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('sistema_operacional', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('desativado', 'Desativado')], max_length=20)),
                ('data_inclusao', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
