# Generated by Django 5.2 on 2025-04-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='teste',
            field=models.CharField(default=1212, max_length=100),
            preserve_default=False,
        ),
    ]
