# Generated by Django 5.2 on 2025-04-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_servidor_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='update',
            field=models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('marco', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Outubro'), ('outubro', 'Setembro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro'), ('sem update', 'Sem Update')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
