# Generated by Django 5.2 on 2025-04-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_servidor_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='teste',
        ),
        migrations.AddField(
            model_name='servidor',
            name='backup',
            field=models.CharField(choices=[('Baixo', 'baixo'), ('Medio', 'medio'), ('Alto', 'alto'), ('Sem Backup', 'sembackup')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
