# Generated by Django 5.2 on 2025-04-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_servidor_teste_servidor_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='backup',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Sem Backup', 'Sem Backup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='localizacao',
            field=models.CharField(choices=[('Lever', 'Lever'), ('Ramalde', 'Ramalde'), ('Gaia', 'Gaia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('A Fazer', 'A Fazer'), ('Lixo', 'Lixo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='update',
            field=models.CharField(choices=[('CRIT', 'CRIT'), ('PROD', 'PROD'), ('HOMU', 'HOMU'), ('Sem Update', 'Sem Update')], max_length=20),
        ),
    ]
