services:
  - type: web
    name: gestao-servidores
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn gestao_servidores.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
